"""empty message

Revision ID: 165ea3e868f1
Revises: c0b6ab5ea9d0
Create Date: 2025-02-15 18:28:39.622734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165ea3e868f1'
down_revision = 'c0b6ab5ea9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_in_use',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('in_use', sa.Enum('true', name='inuse'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('in_use'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('user_interaction', schema=None) as batch_op:
        batch_op.drop_column('overmode_exp_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_interaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overmode_exp_date', sa.DATETIME(), nullable=True))

    op.drop_table('calendar_in_use')
    # ### end Alembic commands ###
