"""empty message

Revision ID: e0cc9c6a63e4
Revises: 
Create Date: 2022-10-03 22:15:23.615729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0cc9c6a63e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('overruled_status', sa.Boolean(), nullable=True),
    sa.Column('overruled_exp_date', sa.DateTime(), nullable=True),
    sa.Column('overmode_status', sa.Enum('ECO', 'CONFORT', 'UNKNOWN', name='overmode'), nullable=True),
    sa.Column('overmode_exp_date', sa.DateTime(), nullable=True),
    sa.Column('userbonus_status', sa.Boolean(), nullable=True),
    sa.Column('userbonus_exp_date', sa.DateTime(), nullable=True),
    sa.Column('userdown_status', sa.Boolean(), nullable=True),
    sa.Column('userdown_exp_date', sa.DateTime(), nullable=True),
    sa.Column('targettemp', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_interaction')
    # ### end Alembic commands ###
